# -*- coding: utf-8 -*-
from . import (
    partner_ext,
    pricelist_ext,
    saycare_specialty,
    saycare_service,
    saycare_visit,
    saycare_medication_order,
    saycare_vital_signs,
    saycare_clinical_note,
    saycare_lab_order,
    saycare_rad_order,
    saycare_appointment,
    saycare_patient_history,
    account_journal_ext,
    account_move_ext,
    saycare_medicine,
    hospital_inpatient_department,
    hospital_floor,
    hospital_room,
    hospital_accommodation_grade,
    hospital_bed,
)
